### ISSUE TITLE
Provide option for non-USA specific date format(s)

### ISSUE THREAD

**Issue by sammcj** [nexional/ConvertEpochToDate#1]
> '%m/%d/%y %H:%M:%S.ms e.g. 01/02/19 14:00:30.786'

This is a USA specific way of formatting dates and is very confusing to people from the rest of the world (most of us read left to right and small to large etc... but that debate is not for this feature / bug report).

It would be good if this could use `DD/MM/YYYY`, `YYYY.MM.DD` or even better - have it set by your locale for you.

![screen shot 2019-02-19 at 1 05 25 pm](https://user-images.githubusercontent.com/862951/52985236-0bfd9000-3447-11e9-8157-1be97ddb5a57.jpg)

Source: https://en.wikipedia.org/wiki/Date_format_by_country

**Comment by nexional** [comment]
I updated the output date format to more generic %a %d %b %Y %H:%M:%S.ms e.g. Tue 01 Jan 2019 01:02:34.786 at the moment. Will explore later on how to display in regional long date.

**Comment by sammcj** [comment]
Cool - that’s great and what a quick response!

Legend :)

--
Sam McLeod

**Comment by nexional** [comment]
Package now has customizable option "output_date_format" among other new features in v2.

**Comment by sammcj** [comment]
Great work and thank you! :)

--
Sam McLeod

**Comment by sammcj** [comment]
Awesome I'm now using:

```json
{
  "output_date_format": "%a %d %m %Y %I:%M:%S %p",
}
```

Which changes:

`1551307884`

to

`Thu 28 02 2019 09:51:24 AM + 000ms`

Thanks again!
